global:
  scrape_interval: 1s  # How often to scrape targets by default.

scrape_configs:
  - job_name: 'snowflake-server'
    static_configs:
      - targets: ['server:9464']

  - job_name: 'snowflake-temporal-worker'
    static_configs:
      - targets: ['temporal-worker:9464']

  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']
