# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: snowflake/temporal/v1/snowflake_activity.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .snowflake import v1


@dataclass
class NextSnowflakeActivityInput(betterproto.Message):
    """Input message for Snowflake activities in Temporal workflows."""

    # If true, the activity will wait until a Snowflake ID is available.
    wait: bool = betterproto.bool_field(1)


@dataclass
class NextSnowflakeActivityOutput(betterproto.Message):
    """Output message for Snowflake activities in Temporal workflows."""

    # The generated Snowflake ID.
    snowflake: v1.Snowflake = betterproto.message_field(1)


@dataclass
class BatchNextSnowflakeActivityInput(betterproto.Message):
    """Input message for batch Snowflake activities in Temporal workflows."""

    # The number of Snowflake IDs to generate.
    count: int = betterproto.int32_field(1)
    # If true, the activity will wait until Snowflake IDs are available.
    wait: bool = betterproto.bool_field(2)


@dataclass
class BatchNextSnowflakeActivityOutput(betterproto.Message):
    """Output message for batch Snowflake activities in Temporal workflows."""

    # The generated Snowflake IDs.
    snowflakes: List[v1.Snowflake] = betterproto.message_field(1)
