// @generated by protoc-gen-es v2.9.0 with parameter "target=ts,import_extension=js"
// @generated from file snowflake/temporal/v1/snowflake_activity.proto (package snowflake.temporal.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Snowflake } from "../../v1/snowflake_pb.js";
import { file_snowflake_v1_snowflake } from "../../v1/snowflake_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file snowflake/temporal/v1/snowflake_activity.proto.
 */
export const file_snowflake_temporal_v1_snowflake_activity: GenFile = /*@__PURE__*/
  fileDesc("Ci5zbm93Zmxha2UvdGVtcG9yYWwvdjEvc25vd2ZsYWtlX2FjdGl2aXR5LnByb3RvEhVzbm93Zmxha2UudGVtcG9yYWwudjEiKgoaTmV4dFNub3dmbGFrZUFjdGl2aXR5SW5wdXQSDAoEd2FpdBgBIAEoCCJJChtOZXh0U25vd2ZsYWtlQWN0aXZpdHlPdXRwdXQSKgoJc25vd2ZsYWtlGAEgASgLMhcuc25vd2ZsYWtlLnYxLlNub3dmbGFrZSI+Ch9CYXRjaE5leHRTbm93Zmxha2VBY3Rpdml0eUlucHV0Eg0KBWNvdW50GAEgASgFEgwKBHdhaXQYAiABKAgiTwogQmF0Y2hOZXh0U25vd2ZsYWtlQWN0aXZpdHlPdXRwdXQSKwoKc25vd2ZsYWtlcxgBIAMoCzIXLnNub3dmbGFrZS52MS5Tbm93Zmxha2VCZlpkZ2l0aHViLmNvbS9hbWFyaS9zbm93Zmxha2UtbW9ub3JlcG8vc25vd2ZsYWtlLWdvL3BrZy9wcm90by9zbm93Zmxha2UvdGVtcG9yYWwvdjE7c25vd2ZsYWtldGVtcG9yYWx2MWIGcHJvdG8z", [file_snowflake_v1_snowflake]);

/**
 * Input message for Snowflake activities in Temporal workflows.
 *
 * @generated from message snowflake.temporal.v1.NextSnowflakeActivityInput
 */
export type NextSnowflakeActivityInput = Message<"snowflake.temporal.v1.NextSnowflakeActivityInput"> & {
  /**
   * If true, the activity will wait until a Snowflake ID is available.
   *
   * @generated from field: bool wait = 1;
   */
  wait: boolean;
};

/**
 * Describes the message snowflake.temporal.v1.NextSnowflakeActivityInput.
 * Use `create(NextSnowflakeActivityInputSchema)` to create a new message.
 */
export const NextSnowflakeActivityInputSchema: GenMessage<NextSnowflakeActivityInput> = /*@__PURE__*/
  messageDesc(file_snowflake_temporal_v1_snowflake_activity, 0);

/**
 * Output message for Snowflake activities in Temporal workflows.
 *
 * @generated from message snowflake.temporal.v1.NextSnowflakeActivityOutput
 */
export type NextSnowflakeActivityOutput = Message<"snowflake.temporal.v1.NextSnowflakeActivityOutput"> & {
  /**
   * The generated Snowflake ID.
   *
   * @generated from field: snowflake.v1.Snowflake snowflake = 1;
   */
  snowflake?: Snowflake;
};

/**
 * Describes the message snowflake.temporal.v1.NextSnowflakeActivityOutput.
 * Use `create(NextSnowflakeActivityOutputSchema)` to create a new message.
 */
export const NextSnowflakeActivityOutputSchema: GenMessage<NextSnowflakeActivityOutput> = /*@__PURE__*/
  messageDesc(file_snowflake_temporal_v1_snowflake_activity, 1);

/**
 * Input message for batch Snowflake activities in Temporal workflows.
 *
 * @generated from message snowflake.temporal.v1.BatchNextSnowflakeActivityInput
 */
export type BatchNextSnowflakeActivityInput = Message<"snowflake.temporal.v1.BatchNextSnowflakeActivityInput"> & {
  /**
   * The number of Snowflake IDs to generate.
   *
   * @generated from field: int32 count = 1;
   */
  count: number;

  /**
   * If true, the activity will wait until Snowflake IDs are available.
   *
   * @generated from field: bool wait = 2;
   */
  wait: boolean;
};

/**
 * Describes the message snowflake.temporal.v1.BatchNextSnowflakeActivityInput.
 * Use `create(BatchNextSnowflakeActivityInputSchema)` to create a new message.
 */
export const BatchNextSnowflakeActivityInputSchema: GenMessage<BatchNextSnowflakeActivityInput> = /*@__PURE__*/
  messageDesc(file_snowflake_temporal_v1_snowflake_activity, 2);

/**
 * Output message for batch Snowflake activities in Temporal workflows.
 *
 * @generated from message snowflake.temporal.v1.BatchNextSnowflakeActivityOutput
 */
export type BatchNextSnowflakeActivityOutput = Message<"snowflake.temporal.v1.BatchNextSnowflakeActivityOutput"> & {
  /**
   * The generated Snowflake IDs.
   *
   * @generated from field: repeated snowflake.v1.Snowflake snowflakes = 1;
   */
  snowflakes: Snowflake[];
};

/**
 * Describes the message snowflake.temporal.v1.BatchNextSnowflakeActivityOutput.
 * Use `create(BatchNextSnowflakeActivityOutputSchema)` to create a new message.
 */
export const BatchNextSnowflakeActivityOutputSchema: GenMessage<BatchNextSnowflakeActivityOutput> = /*@__PURE__*/
  messageDesc(file_snowflake_temporal_v1_snowflake_activity, 3);

