{
 "title": "Snowflake - RED",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   { "name": "interval", "query": "1m,5m,15m,30m,1h,3h,6h" },
   {
    "name": "rpc_service",
    "query": {
     "query": "label_values(rpc_server_duration_milliseconds_count{job=~\"$job\"},rpc_service)"
    }
   },
   {
    "name": "rpc_method",
    "query": {
     "query": "label_values(rpc_server_duration_milliseconds_count{job=~\"$job\",rpc_service=~\"$rpc_service\"},rpc_method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (rpc_service, rpc_method) (rate(rpc_server_requests_per_rpc_sum{job=~\"$job\"}[$interval]))",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    },
    {
     "expr": "sum (rate(rpc_server_requests_per_rpc_sum{job=~\"$job\"}[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Snowflakes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "snowflakes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "increase(snowflakes_total[1y])" }
   ]
  },
  {
   "title": "Snowflakes per Second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "snowflakes/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(snowflakes_total[$interval])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by (le, rpc_service, rpc_method) (\n    rate(rpc_server_duration_milliseconds_bucket{rpc_service=~\"$rpc_service\", rpc_method=~\"$rpc_method\"}[$interval])\n  )\n)",
     "legendFormat": "p99 - {{rpc_service}}/{{rpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum by (le, rpc_service, rpc_method) (\n    rate(rpc_server_duration_milliseconds_bucket{rpc_service=~\"$rpc_service\", rpc_method=~\"$rpc_method\"}[$interval])\n  )\n)",
     "legendFormat": "p95 - {{rpc_service}}/{{rpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.50,\n  sum by (le, rpc_service, rpc_method) (\n    rate(rpc_server_duration_milliseconds_bucket{rpc_service=~\"$rpc_service\", rpc_method=~\"$rpc_method\"}[$interval])\n  )\n)",
     "legendFormat": "p50 - {{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  {
   "title": "Error Rate by RPC",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (rpc_service, rpc_method) (increase(rpc_server_requests_per_rpc_sum{job=~\"$job\",rpc_service=~\"$rpc_service\",rpc_method=~\"$rpc_method\",rpc_grpc_status_code!=\"0\"}[$interval]))) / (sum by (rpc_service, rpc_method) (increase(rpc_server_requests_per_rpc_sum{job=~\"$job\",rpc_service=~\"$rpc_service\",rpc_method=~\"$rpc_method\"}[$interval])))",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (le) (rate(rpc_server_duration_milliseconds_bucket{rpc_service=~\"$rpc_service\",rpc_method=~\"$rpc_method\"}[$interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rpc_grpc_status_code) (\n  increase(\n    rpc_server_requests_per_rpc_sum{\n      job=~\"$job\",\n      rpc_service=~\"$rpc_service\",\n      rpc_method=~\"$rpc_method\",\n      rpc_grpc_status_code!=\"0\"\n    }[$interval]\n  )\n)\n/\nignoring(rpc_grpc_status_code) group_left\nsum (\n  increase(\n    rpc_server_requests_per_rpc_sum{\n      job=~\"$job\",\n      rpc_service=~\"$rpc_service\",\n      rpc_method=~\"$rpc_method\",\n      rpc_grpc_status_code!=\"0\"\n    }[$interval]\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}