// @generated by protoc-gen-es v2.9.0 with parameter "target=ts,import_extension=js"
// @generated from file snowflake/v1/snowflake.proto (package snowflake.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file snowflake/v1/snowflake.proto.
 */
export const file_snowflake_v1_snowflake: GenFile = /*@__PURE__*/
  fileDesc("Chxzbm93Zmxha2UvdjEvc25vd2ZsYWtlLnByb3RvEgxzbm93Zmxha2UudjEiNgoJU25vd2ZsYWtlEhMKC2ludDY0X3ZhbHVlGAEgASgDEhQKDHN0cmluZ192YWx1ZRgCIAEoCUJVWlNnaXRodWIuY29tL2FtYXJpL3Nub3dmbGFrZS1tb25vcmVwby9zbm93Zmxha2UtZ28vcGtnL3Byb3RvL3Nub3dmbGFrZS92MTtzbm93Zmxha2V2MWIGcHJvdG8z");

/**
 * Snowflake represents a unique identifier generated by the Snowflake algorithm.
 *
 * @generated from message snowflake.v1.Snowflake
 */
export type Snowflake = Message<"snowflake.v1.Snowflake"> & {
  /**
   * 64-bit integer representation of the Snowflake ID.
   * This is the primary representation used in most applications and is more compact than the string representation.
   *
   * @generated from field: int64 int64_value = 1;
   */
  int64Value: bigint;

  /**
   * String representation of the Snowflake ID.
   * This is useful for systems that cannot handle 64-bit integers, such as JavaScript.
   *
   * @generated from field: string string_value = 2;
   */
  stringValue: string;
};

/**
 * Describes the message snowflake.v1.Snowflake.
 * Use `create(SnowflakeSchema)` to create a new message.
 */
export const SnowflakeSchema: GenMessage<Snowflake> = /*@__PURE__*/
  messageDesc(file_snowflake_v1_snowflake, 0);

