// @generated by protoc-gen-es v2.9.0 with parameter "target=ts,import_extension=js"
// @generated from file snowflake/v1/snowflake_service.proto (package snowflake.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Snowflake } from "./snowflake_pb.js";
import { file_snowflake_v1_snowflake } from "./snowflake_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file snowflake/v1/snowflake_service.proto.
 */
export const file_snowflake_v1_snowflake_service: GenFile = /*@__PURE__*/
  fileDesc("CiRzbm93Zmxha2UvdjEvc25vd2ZsYWtlX3NlcnZpY2UucHJvdG8SDHNub3dmbGFrZS52MSIkChROZXh0U25vd2ZsYWtlUmVxdWVzdBIMCgR3YWl0GAEgASgIIkMKFU5leHRTbm93Zmxha2VSZXNwb25zZRIqCglzbm93Zmxha2UYASABKAsyFy5zbm93Zmxha2UudjEuU25vd2ZsYWtlIj0KGUJhdGNoTmV4dFNub3dmbGFrZVJlcXVlc3QSEgoKYmF0Y2hfc2l6ZRgBIAEoBRIMCgR3YWl0GAIgASgIIkkKGkJhdGNoTmV4dFNub3dmbGFrZVJlc3BvbnNlEisKCnNub3dmbGFrZXMYASADKAsyFy5zbm93Zmxha2UudjEuU25vd2ZsYWtlMtUBChBTbm93Zmxha2VTZXJ2aWNlElgKDU5leHRTbm93Zmxha2USIi5zbm93Zmxha2UudjEuTmV4dFNub3dmbGFrZVJlcXVlc3QaIy5zbm93Zmxha2UudjEuTmV4dFNub3dmbGFrZVJlc3BvbnNlEmcKEkJhdGNoTmV4dFNub3dmbGFrZRInLnNub3dmbGFrZS52MS5CYXRjaE5leHRTbm93Zmxha2VSZXF1ZXN0Giguc25vd2ZsYWtlLnYxLkJhdGNoTmV4dFNub3dmbGFrZVJlc3BvbnNlQlVaU2dpdGh1Yi5jb20vYW1hcmkvc25vd2ZsYWtlLW1vbm9yZXBvL3Nub3dmbGFrZS1nby9wa2cvcHJvdG8vc25vd2ZsYWtlL3YxO3Nub3dmbGFrZXYxYgZwcm90bzM", [file_snowflake_v1_snowflake]);

/**
 * Request message for SnowflakeService.
 *
 * @generated from message snowflake.v1.NextSnowflakeRequest
 */
export type NextSnowflakeRequest = Message<"snowflake.v1.NextSnowflakeRequest"> & {
  /**
   * If true, waits until a new ID can be generated if the sequence overflows.
   *
   * @generated from field: bool wait = 1;
   */
  wait: boolean;
};

/**
 * Describes the message snowflake.v1.NextSnowflakeRequest.
 * Use `create(NextSnowflakeRequestSchema)` to create a new message.
 */
export const NextSnowflakeRequestSchema: GenMessage<NextSnowflakeRequest> = /*@__PURE__*/
  messageDesc(file_snowflake_v1_snowflake_service, 0);

/**
 * Response message for SnowflakeService.
 *
 * @generated from message snowflake.v1.NextSnowflakeResponse
 */
export type NextSnowflakeResponse = Message<"snowflake.v1.NextSnowflakeResponse"> & {
  /**
   * @generated from field: snowflake.v1.Snowflake snowflake = 1;
   */
  snowflake?: Snowflake;
};

/**
 * Describes the message snowflake.v1.NextSnowflakeResponse.
 * Use `create(NextSnowflakeResponseSchema)` to create a new message.
 */
export const NextSnowflakeResponseSchema: GenMessage<NextSnowflakeResponse> = /*@__PURE__*/
  messageDesc(file_snowflake_v1_snowflake_service, 1);

/**
 * Request message for batch Snowflake generation.
 *
 * @generated from message snowflake.v1.BatchNextSnowflakeRequest
 */
export type BatchNextSnowflakeRequest = Message<"snowflake.v1.BatchNextSnowflakeRequest"> & {
  /**
   * @generated from field: int32 batch_size = 1;
   */
  batchSize: number;

  /**
   * If true, waits until new IDs can be generated if the sequence overflows.
   *
   * @generated from field: bool wait = 2;
   */
  wait: boolean;
};

/**
 * Describes the message snowflake.v1.BatchNextSnowflakeRequest.
 * Use `create(BatchNextSnowflakeRequestSchema)` to create a new message.
 */
export const BatchNextSnowflakeRequestSchema: GenMessage<BatchNextSnowflakeRequest> = /*@__PURE__*/
  messageDesc(file_snowflake_v1_snowflake_service, 2);

/**
 * Response message for batch Snowflake generation.
 *
 * @generated from message snowflake.v1.BatchNextSnowflakeResponse
 */
export type BatchNextSnowflakeResponse = Message<"snowflake.v1.BatchNextSnowflakeResponse"> & {
  /**
   * @generated from field: repeated snowflake.v1.Snowflake snowflakes = 1;
   */
  snowflakes: Snowflake[];
};

/**
 * Describes the message snowflake.v1.BatchNextSnowflakeResponse.
 * Use `create(BatchNextSnowflakeResponseSchema)` to create a new message.
 */
export const BatchNextSnowflakeResponseSchema: GenMessage<BatchNextSnowflakeResponse> = /*@__PURE__*/
  messageDesc(file_snowflake_v1_snowflake_service, 3);

/**
 * SnowflakeService provides methods to generate unique Snowflake IDs.
 *
 * @generated from service snowflake.v1.SnowflakeService
 */
export const SnowflakeService: GenService<{
  /**
   * Generate the next unique Snowflake ID.
   *
   * @generated from rpc snowflake.v1.SnowflakeService.NextSnowflake
   */
  nextSnowflake: {
    methodKind: "unary";
    input: typeof NextSnowflakeRequestSchema;
    output: typeof NextSnowflakeResponseSchema;
  },
  /**
   * Generate a batch of unique Snowflake IDs.
   *
   * @generated from rpc snowflake.v1.SnowflakeService.BatchNextSnowflake
   */
  batchNextSnowflake: {
    methodKind: "unary";
    input: typeof BatchNextSnowflakeRequestSchema;
    output: typeof BatchNextSnowflakeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_snowflake_v1_snowflake_service, 0);

