[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version="1.48.0", features = ["macros", "rt-multi-thread"]}

snowflake_proto = { path = "../../snowflake-rust/snowflake-proto" }