apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Use the Prometheus service name and port
    isDefault: true
    editable: true
    uid: PBFA97CFB590B2093
    